### ISSUE TITLE
Add a trigger for the ethnio signup form

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1143]
So that users can sign up to help with usability testing even after they close the ethnio pop up, add a button to either the footer or the feedback box to trigger the popup.

**Tasks:**
- [x] @jenniferthibault can you find a good place for this to go?
- [x] I'll add it on the web app
- [x] Add it on the CMS

**Comment by emileighoutlaw** [comment]
Do we want to just have content on the button? It seems like maybe we need a button and a little microcopy, something along the lines of

Help improve betaFEC (text)
[Sign up for a sneak peek] (button)

**Comment by noahmanger** [comment]
I like that idea!

**Comment by jenniferthibault** [comment]
Here's how we could integrate that call to action in the feedback tool. It would need to be placed on two screens—once on the first feedback screen, once on the submitted/success screen.

![screen shot 2016-03-30 at 12 10 36 pm](https://cloud.githubusercontent.com/assets/11636908/14149077/7486cbfe-f670-11e5-899a-5c8c34a89f10.png)

We already had a lot of that language on the feedback tool screen, so I added in a more explanatory copy format, but all the microcopy is up to your guidance @emileighoutlaw !

I don't think I'd put this in the footer as well, for the principal of put things in one place and only one place, this feedback tool makes a logical grouping.

**Comment by emileighoutlaw** [comment]
Love this Jen! It's so much easier to work with the language when I can envision the design. _Thank you._

How about for the first page (initial popup):
> Leave feedback here, or sign up to help us test new features. 

And then on the submission screen:
> Every week, we ask people to try out new features, as we design them. Sign up to join our list of testers.

or

> Each week, we ask people to try out new features that we're working on. Sign up to join our list of testers.

**Comment by noahmanger** [comment]
:+1: sounds good! Hope to get to this tomorrow.

**Comment by noahmanger** [comment]
I was going to tackle this, but then realized we should wait until this is merged in: https://github.com/18F/openFEC-web-app/pull/1110

**Comment by noahmanger** [comment]
So, I'm thinking on this again and after we move to an externalized feedback library, it will make it tougher to implement the ethnio trigger as part of the feedback form. @jenniferthibault what do you think about including it just in the footer? Is it weird and duplicative of the feedback button? From one angle, they're different asks: Give us Feedback vs. Sign up to be a participant. 

Not a huge deal, but if we went this route I could just do it and wouldn't be blocked.

**Comment by jenniferthibault** [comment]
Recapping an IRL convo:

I think we should wait until the signup can go into the feedback module, because it feels like it would get missed in the footer. Putting it in the footer gets it on the page faster, but doesn't put it where people are already looking for feedback/engagement opportunities, so it wouldn't really help. 

Holding (and knowingly blocked) until we can get it in there.
