### ISSUE TITLE
Implement new strategy for "Help for candidates and committees" landing page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2287]
Discussion and history in https://github.com/18F/openFEC-web-app/issues/2185 

@xtine @lbeaufort @dorothyyeager 
___

### Designs
![screen shot 2017-09-06 at 6 23 26 pm](https://user-images.githubusercontent.com/11636908/30137263-802dea6a-9330-11e7-8e04-1dabe3b79847.png)

### Notes

**Links**
- Guides:
  - Each card links to the corresponding page created by the implementation of this issue: https://github.com/18F/openFEC-web-app/issues/2286
- Contribution limits: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits-candidates/
- All tips: https://www.fec.gov/updates/?update_type=tips-for-treasurers
- Electronic filing information: https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/
- Forms: https://www.fec.gov/help-candidates-and-committees/forms
- Dates and deadlines: https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines
- Education and learning: https://transition.fec.gov/info/outreach.shtml
- You might also like
  - Search for your committee's information and filings: https://www.fec.gov/data/advanced/?tab=filings
  - Statements of candidacy filed by office: https://www.fec.gov/data/filings/?data_type=processed&form_type=F2
  - Statements of organization filed by committees: https://www.fec.gov/data/filings/?data_type=processed&form_type=F1
  - Enforcement overview: https://www.fec.gov/legal-resources/enforcement/
  - Search matters under review (MURs): https://www.fec.gov/data/legal/search/enforcement/?search_type=murs&search=&mur_no=&mur_respondents=
  - Search advisory opinions (AOs): https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F
  - Find and contact your analyst: https://www.fec.gov/help-candidates-and-committees/question-rad/

**Tasks to completion:**

- [x] Add list of links to this issue
- [x] @jenniferthibault finalizes and exports images, icons (should not block the rest of implementation)
- [x] Connect glossary definitions to MURs and AOs
- [x] Create independent links to guidance for each type of committee (connects to https://github.com/18F/openFEC-web-app/issues/2286)
- [x] Match designs above
- [x] Check mobile readiness

Dependencies
- [x] Finalize design and language with stakehoders
- [x] Content in accessible doc
- [x] Wait for CMS and web app merger

**Comment by AmyKort** [comment]
@dorothyyeager and @gsmaragdis -- just flagging this one for you.

**Comment by xtine** [comment]
@jenniferthibault: I just realized that this page is one of the tour pages. The points currently are at the Hero heading, Dates and deadlines section, and sidebar. How are these going to be changed?

**Comment by xtine** [comment]
@johnnyporkchops: did you want to get started on this? I've written some notes, and then we can also pair with @dorothyyeager and @lbeaufort once you've gotten started.

/fec-cms/fec/home/templates/candidate-and-committee-services/services_landing_page.html

- Remove all HTML after the hero section
- Start with a div with `container` and `main` classes
- Keep `{% include 'partials/disclaimer.html' %}` after closing container div

Hero
- Edit description in Wagtail

Guides
- h2 heading
- 4 wide grid with secondary card icons
    - make new icon (notebook)

Popular Topics
- div with class `option u-margin—top`
- 2 wide grid
    - tips for treasurer heading uses `heading--section heading--with-action` classes, look at home page for reference how this is used
    - All tips button is `button--alt`

**Comment by jenniferthibault** [comment]
@xtine Based on https://github.com/18F/fec-cms/issues/1251 @AmyKort did a quick slack convo and it looked like the preference was to turn the site tour off—so I think don't need to account for the tour adjustment for this issue.

**Comment by AmyKort** [comment]
Thanks!

**Comment by johnnyporkchops** [comment]
"You might also like" text and links for when we rebuild the page in wagtail on prod:
### You might also like
**Look up information reported and filed with the FEC**
[Search for your committee's information and filings](https://www.fec.gov/data/advanced/?tab=filings)
[Statements of candidacy filed by office](https://www.fec.gov/data/filings/?data_type=processed&form_type=F2)
[Statements of organization filed by committees](https://www.fec.gov/data/filings/?data_type=processed&form_type=F1)

**Learn about enforcement of federal campaign finance law**
[Enforcement overview](https://www.fec.gov/legal-resources/enforcement/)
[Search matters under review (MURs)](https://www.fec.gov/datahttps://www.fec.gov/legal/search/enforcement/?search_type=murs&search=&mur_no=&mur_respondents=)
[Search advisory opinions (AOs)](https://www.fec.gov/datahttps://www.fec.gov/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F)

**Get help from an FEC analyst**
[Find and contact your analyst](https://www.fec.gov/help-candidates-and-committees/question-rad/)

**Comment by jenniferthibault** [comment]
📁 [Zipped images file](https://github.com/18F/openFEC-web-app/files/1356241/helpfor-landing-images.zip)

cc @johnnyporkchops 

I included .jpg and .png at 1x & 2x — please rename the files as needed, I'm not sure what the naming conventions you @xtine and @patphongs are following

**Comment by patphongs** [comment]
Will get to this in this sprint and try to get it merged into dev in time for the upcoming November conference testing.

**Comment by patphongs** [comment]
Reviewed this today and things are looking good. We discussed the new naming convention for images and updating the infoblock image implementation to be more consistent throughout. In design pairing, we'll sync up about any loose ends before merging this in.

**Comment by patphongs** [comment]
This has been completed and merged into dev from this PR https://github.com/18F/fec-cms/pull/1441
