### ISSUE TITLE
Mock up pages in new design style

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#476]
**Goal:** Decide what these designs look like in the new visual system, and incorporate user research findings 

**Pages to be designed:**
- [x] Election data page. See #481 
- [x] Zip code search. See #471 
- [x] Search results See #444
- [x] Candidate Page & Committee Page relationship, elements
- [x] Elections pages. See #521 

cc @noahmanger these are the priorities as I understand them
