### ISSUE TITLE
Update meta tag content and images on app and cms

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#718]
We need to update the share image and favicons on both the main site and the app, as well as content that shows up when sharing a page on social media.

@emileighoutlaw do you want to take the content on and @jenniferthibault the icons?

The code / copy currently lives here: https://github.com/18F/openFEC-web-app/blob/8373db749a3d8f13baae0774610e5d27e6b44024/templates/partials/meta-tags.html#L2

**Comment by noahmanger** [comment]
I believe most favicon generators do this already, but make sure to include an iOS homescreen icon per https://github.com/18F/openFEC-web-app/issues/721

**Comment by jenniferthibault** [comment]
Yes! I was thinking about this last week. We should also find some way to test this, because I don't *think* it worked when we designed it and hooked it up for the API.

**Comment by leahbannon** [comment]
related to https://github.com/18F/openFEC/issues/1216

**Comment by jenniferthibault** [comment]
@noahmanger helped me break this down into 3 categories that need to be designed, and should feel consistent across platforms:
- [ ]  Social sharing images & headlines (facebook/twitter) More details on specs [here](https://dev.twitter.com/cards/types/summary-large-image)
  - [ ] Image
  - [ ] Title @emileighoutlaw 
  - [ ] Description @emileighoutlaw 
- [ ]  Favicon for browser tabs
- [ ]  "App" images (For when you save or bookmark something to your homescreen)



##### Social Sharing images
For social sharing images (facebook, twitter) I'm thinking something simple without marketing text, that intros the URL and previews FEC branding, like the following:

![artboard 1 copy 3](https://cloud.githubusercontent.com/assets/11636908/10059282/16bd238e-6218-11e5-875b-57ebf346e5ee.png)

##### Browser favicon
For the browser favicon, I'm thinking we use a simplified version of the seal (without text) so that it can be a little larger and more distinguishable:
![favicon](https://cloud.githubusercontent.com/assets/11636908/10059827/30635242-621b-11e5-8451-f0257afe96b7.png)

For comparison, here's the current one on fec.gov:
![current-favicon](https://cloud.githubusercontent.com/assets/11636908/10059879/76223244-621b-11e5-8340-8c36bdf4c6e0.png)


##### App images
For App images, I'm thinking we can shorten the URL, and give a peek of the seal, or drop the seal entirely. 

1 ![artboard 1 copy 4](https://cloud.githubusercontent.com/assets/11636908/10059583/da06f670-6219-11e5-990c-512d609bbfa1.png)
2 ![artboard 1 copy 5](https://cloud.githubusercontent.com/assets/11636908/10059584/da0a5bf8-6219-11e5-86e3-92575e88efd0.png)
3 ![artboard 1 copy 6](https://cloud.githubusercontent.com/assets/11636908/10059585/da0d4bd8-6219-11e5-9557-0cb46e435c43.png)

Thoughts? cc @leahbannon / @LindsayYoung

**Comment by leahbannon** [comment]
For the app, I like the second design. I'm not sure about shortening to a incorrect link, though. How about removing the dot so it's betaFEC? I think that's what we're calling it in the blog post.

**Comment by jenniferthibault** [comment]
Yessss. Helpful and certainly do-able!

Here are a few alternate favicons I'm kicking around based on the data flag, h/t @leahbannon :
![artboard 8 copy 3](https://cloud.githubusercontent.com/assets/11636908/10060787/8da491ae-6221-11e5-8282-210e65018fb4.png)
![artboard 8 copy 5](https://cloud.githubusercontent.com/assets/11636908/10060788/8da58a50-6221-11e5-9e56-75e54ca3aedb.png)

 I think the first, on the light background, is the most clear and distinguishable, even at that size

**Comment by leahbannon** [comment]
I agree that the first one is more distinguishable -- I like that one :)

**Comment by noahmanger** [comment]
Nice! I like the second app icon. But I think I prefer the simplified seal favicon though. It'll feel more relevant across both parts of the site, and also feels more government-y, albeit subtly.

**Comment by jenniferthibault** [comment]
Visually I do like the flag/graph favicon, but I think that the simplified seal will tie it to fec.gov more closely. Going to go with that for now, and the second app icon with the text adjusted to betaFEC.

**Comment by jenniferthibault** [comment]
https://github.com/18F/fec-style/pull/118 put all the images into the FEC style repo

**Comment by jenniferthibault** [comment]
Moved assignment to Emileigh to wrap up text. Woo!

**Comment by noahmanger** [comment]
Remove references to "@18F" on twitter meta tags (h/t @konklone )
