### ISSUE TITLE
Design interaction for cap on number of records that can be exported

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#975]
**[Story](https://18f.storiesonboard.com/m/fec/!card/EurTUqJOirh4DjnUgNBiGw)**: So that users cannot request a huge collection of resources that bogs the site down, impose a conservative cap on the number of records they can request.

**Goal:** We need to figure out how we communicate the export limit of 100,000 records to the user in some way or another. There's two major routes:

1. We do not allow them to request an export if there's more than 100,000 records in the dataset. In this case we need to figure out:
- State of the export button (simply disabled or something else?)
- Provide help messaging with instructions for how to limit their download or direct them to the bulk downloads on fec.gov

2. Alternatively, we could simply provide the first 100,000 records of whatever they requested. This would require:
- Explaining that this is what we're doing
- Provide instructions for how to get the full dataset

**Tasks**
- [x] Agree on #1 or #2 (or if there's a third option) here
- [x] @jenniferthibault mock it up
- [x] @emileighoutlaw help with content
- [ ] Implement the backend
- [ ] Implement the frontend

**Comment by jenniferthibault** [comment]
Transcribing a bit from today's discussion in Slack, we want to only allow the export button to become active if a users' query is under 100,000 records. 

We're not going to just give the first 100,000 because it would be harder for a person to try and create a query that will give them the next 100,000. but if they are creating the query themselves the first time, they can use dates or something to make it systematic. There isn't really a use case where having half of the records you want is useful. 

We'll get a small proportion of both false negatives and false positives. False negatives mean we deny requests that we should allow—the request only has 90k records, but our approximate count says there are 110k. False positives mean we allow requests that we should deny. 

To help explain this, we need to give the user 3 points of info:
 - `Exports are available for fewer than 100,000 records.` The rule for how many they can download. 
 - `Add more filters to narrow your results. ` (matching language to the download panel). Instructions for how to narrow the results to fit that parameter. 
 - `To export complete data sets, visit the FEC bulk data exporter.` Where to find ALL the data if they want it.

To me, this seems to fit the need pattern for a tooltip, and might also benefit from grouping the list result count closer to the export button and its rules. 

@emileighoutlaw for wordsmithing? ^

___

### Before:
<img width="824" alt="screen shot 2015-12-07 at 5 16 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/11641982/58cbadb4-9d09-11e5-9560-02c8ffbddd89.png">

___

### After:
With re-grouped page controls. What do you think about this grouping change @noahmanger ? 

<img width="801" alt="screen shot 2015-12-07 at 5 29 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/11641987/68e50902-9d09-11e5-81d6-127ecd7696d0.png">

**Comment by noahmanger** [comment]
Nice. So is the info button only there when the export button is disabled? Or should it always be there, as it has the link to the bulk downloads?

**Comment by jmcarp** [comment]
Proposed backend implementation in https://github.com/jmcarp/openFEC/commit/54880d897ba11be95b68ea40b15f0cb2dfd97305.

**Comment by jenniferthibault** [comment]
HM! My questions back at you should probably be captured as a universal design principle for the site, when we have an answer to it. @emileighoutlaw may be versed in this from her content work.

If a user is following all the rules, should they still be reminded of them?
—Or—
Do we only show the rules if a user isn't meeting the requirements?

**Comment by noahmanger** [comment]
I think in this case it does make more sense to only show it if the button is disabled. Should we though use a different icon, maybe the exclamation point? That's more of a warning, and makes sense to be conditional.

**Comment by jenniferthibault** [comment]
I can see both sides, but see nothing wrong with trying that route first. @onezerojeremy do you have thoughts or hunches?

**Comment by onezerojeremy** [comment]
I agree with Noah!  Though I think I'd reserve the "!" point, though. Mostly because browse pages where the limitation is relevant might be common, pre-filtering, and in general I'd save the exclamation point for more dangerous actions. Maybe they aren't though. 

maybe the principle is something like:
"User is made aware of limitations when said limitations are relevant" hmm. maybe. 

Also controversial possibly bad idea: what if we make the disabled button trigger the info box as well. That way people who aren't well versed in what a disabled button looks like and never click info icons still get to find out why their download isn't working. 

though: if we're eventually making big downloads available for popular big searches, like pre-compiled files, does that change how we word the info box, or how we code the disabling of the button (i.e., not based only on number), though i guess that falls into the category of "worry about it later".

**Comment by emileighoutlaw** [comment]
#### Display
I believe it's okay to only show the tooltip when `export` is disabled— if `export` works, folks don't need to know why. I do see the issue with inconsistent use of `i`. Is there another option (other than ` ! `)? For example, could the alert box show when people hover over the disabled button?

#### Vocab
I'm not sure about the word "complete," only because every export is a complete in the sense that it's all the data for the applied filters.Does that make sense? I'm going with "bigger" in my tweaks below. But I'm open to "larger" or other words, if someone has a strong case for it.

#### Content options
Since we're going for scarcity of words, we risk having tiny sentences that sound awfully curt. I'm playing around with punctuation here to soften the tone a little. I have a personal preference, but I'd like to know what y'all think:

>Exports are limited to 100,000 records. Add more filters to narrow results. Export bigger data sets with _FEC bulk data exporter_.

>Exports are limited to 100,000 records: Add filters to narrow results, or export bigger data sets with _FEC bulk data exporter_.

>Exports are limited to 100,000 records— add filters to narrow results, or export bigger data sets with _FEC bulk data exporter_.

**Comment by jenniferthibault** [comment]
Let's go with hovering over the disabled button activate the tooltip, avoiding `i` and `!` conflicts.

Content: Your call @emileighoutlaw, one tiny question: should we add `the` in front of "FEC bulk data exporter? Or is that removed on purpose? I'm all for softening the tone by avoiding curt sentences! I grabbed a random example for the mockup, so don't associate any preference for that over the others with it though!

<img width="787" alt="screen shot 2015-12-08 at 11 48 34 am" src="https://cloud.githubusercontent.com/assets/11636908/11661804/a5519aac-9da1-11e5-9c16-aa82e46f83ce.png">

**Comment by jenniferthibault** [comment]
I know content is still ongoing, but transferring this from design to implementation, and assigning to @noahmanger

**Comment by emileighoutlaw** [comment]
I removed `the` on purpose, but let's add it back in! I do think it looks better.

Option 3 is my preference, content-wise (unless other folks have thoughts).

**Comment by noahmanger** [comment]
This has been implemented.
