### ISSUE TITLE
Add EC and CC tabs to committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#978]
**[Story](https://18f.storiesonboard.com/m/fec/!card/vfBqyymmLoMAzznTwluFuw)**: So that users can understand which Other Spending a committee has conducted, show this information on the committee page.

**Tasks:**
- [x] Add IE tab (merge [current PR](https://github.com/18F/openFEC-web-app/pull/943))
- [x] Add EC tab
- [x] Add CC tab

**Comment by LindsayYoung** [comment]
Dependency:

https://github.com/18F/openFEC/issues/1434

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1058
