### ISSUE TITLE
Link "other spending" aggregate subtotals to itemized views

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#981]
**[Story](https://18f.storiesonboard.com/m/fec/!card/I0bne6Rqsx8cNznTwmRr_g):** So that users can view itemized Independent Expenditures, Communication Costs, and Electioneering Communications, users can filter and browse them all.

**Goal:** Once we've implemented browse pages for each of the other spending categories, link the aggregate subtotals on all pages to them just like we do with receipts and disbursements.

**Tasks:**
- [x] Link subtotals on candidate pages
- [x] Link subtotals on committee pages
- [x] Link subtotals on election pages

**Comment by LindsayYoung** [comment]
Dependency:

18F/openFEC#1434

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1058
